runtime: python310
instance_class: F2

env_variables:
  PYTHONUNBUFFERED: "true"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic 